---
title: "chapter5"
author: "Ella"
date: "21 helmikuuta 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Chapter 5: Dimensionality reduction techniques

##1. Load data, briefly explore the data

```{r}
human <-read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/human2.txt", sep = ",", header = TRUE)
```

```{r}
str(human)

```

```{r}
dim(human)
```

##2. Graphical overview

```{r}
pairs(human, col = "deeppink2")
```


```{r}
summary(human)
```

##3. Principal Component Analysis (unstandardized data)


```{r}
pca_human <- prcomp(human)
```

```{r}
biplot(pca_human, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))
```


##4. Principal Component Analysis (standardized data)

```{r}
human_std <- scale(human)
```

```{r}
summary(human_std)
```

```{r}
pca_human_std <- prcomp(human_std)
```

```{r}
biplot(pca_human_std, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))
```




```{r}
s <-summary(pca_human_std)
s
```


```{r}
pca_pr <- round(100*s$importance[2,], digits = 1) 
pca_pr
```


```{r}
pc_lab <- paste0(names(pca_pr), " (", pca_pr, "%)")
biplot(pca_human_std, cex = c(0.8, 1), col = c("grey40", "deeppink2"), xlab = pc_lab[1], ylab = pc_lab[2])
```




##5.Personal interpretations

##6.Factominer, Multiple Correspondence Analysis 

```{r}
library(FactoMineR)
library(ggplot2)
library(dplyr)
library(tidyr)
data("tea")
```

```{r}
str(tea)
```

```{r}
dim(tea)
```

```{r}
keep_columns <- c("Tea", "How", "how", "sugar", "where", "lunch")
tea_time <- select(tea, one_of(keep_columns))
```

```{r}
summary(tea_time)
```


```{r}
gather(tea) %>% ggplot(aes(value)) + facet_wrap("key", scales = "free") + geom_bar()
```




```{r}
gather(tea_time) %>% ggplot(aes(value)) + facet_wrap("key", scales = "free") + geom_bar() + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```




```{r}
mca <- MCA(tea_time, graph = FALSE)
```


```{r}
summary(mca)
```

```{r}
plot(mca, invisible=c("ind"), habillage = "quali")
```




